### All Patient Requests ###

### Get All
GET http://localhost:3000/api/patients/

### Create
POST http://localhost:3000/api/patients/
Content-Type: application/json

{
	"name": "Alfredo 233",
	"patientNumber": 223330200,
	"birthdayDate": "1990-10-26",
	"contacts": {
		"email": "2302433230@estg.ipp.pt",
		"phone": 203423203
	},
	"symptoms": [
		"cough"
	]
}

### Get By ID
GET http://localhost:3000/api/patients/5ebff4e13a465b29cc1b7303

### Count By Status
GET http://localhost:3000/api/patients/count

### Get One And Update
PUT http://localhost:3000/api/patients/5ecd943b96f5ee0a28851135
Content-Type: application/json

{
	"observations.riskGroup": true
}

### Get One And Delete
DELETE http://localhost:3000/api/patients/5ecd85fe798dfd14244659b7
