### All COVID Tests Requests ###

### Get All
GET http://localhost:3000/api/covid-tests/

### CREATE
POST http://localhost:3000/api/covid-tests/
Content-Type: application/json

{
    "patient":"5ebff8b8c3e5011db4867c9d",
	"notes": "Notes !",
	"date": "2020-05-10"
}

### Get By ID
GET http://localhost:3000/api/covid-tests/5ebff8b8c3e5011db4867c9d

### Get By Patient
GET http://localhost:3000/api/covid-tests/patient/5ebff8b8c3e5011db4867c9d

### Count COVID Tests By Day
GET http://localhost:3000/api/covid-tests/count/day

### Count COVID Tests By Patient
GET http://localhost:3000/api/covid-tests/count/patient

### Get one and update
PUT http://localhost:3000/api/covid-tests/5eb7517e7b60f7302c389c48
Content-Type: application/json

{
	"status": "finished",
    "result": "negative"
}

### Get one and delete
DELETE http://localhost:3000/api/covid-tests/5ebff8c28a6fa81e94bf6c5c