### All Patient Requests ###

### Get All
GET http://localhost:3000/api/patients/

### Create
POST http://localhost:3000/api/patients/
Content-Type: application/json

{
	"name": "Alfredo",
	"patientNumber": 200200200,
	"birthdayDate": "1990-10-26",
	"contacts": {
		"email": "200200200@estg.ipp.pt",
		"phone": 200200200
	},
	"symptoms": [
		"cough"
	]
}

### Get By ID
GET http://localhost:3000/api/patients/5ebff4e13a465b29cc1b7303

### Count By Status
GET http://localhost:3000/api/patients/count

### Get One And Update
PUT http://localhost:3000/api/patients/5ebdbb1e9676038949c89238
Content-Type: application/json

{
	"status": "Suspect"
}

### Get One And Delete
DELETE http://localhost:3000/api/patients/5ebff8b8c3e5011db4867c9d
