### All Users Requests ###

### Get All
GET http://localhost:3000/api/users/

### Create
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "User Name",
	"email": "example@email.com",
	"password": "mypassword123",
	"role": "5eb54c1f44cafe334326a782"
}

### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email": "exemple@email.com",
	"password": "mypassword123"
}

### Get By Id
GET http://localhost:3000/api/users/5eadad03b57e631b6b7c724d

### Get One and Update
PUT http://localhost:3000/api/users/5eadad03b57e631b6b7c724d
Content-Type: application/json

{
    "name": "Name",
	"password": "mypassword124",
}

### Get One And Delete
DELETE http://localhost:3000/api/users/5eadb0f69ed027205e69169f