definitions:
    Role:
        properties:
            name:
                type: string
                required: true
                unique: true
            scopes:
                type: array
                items:
                    type: string
                    enum: ["--view-all", "--edit-all", "--delete-all"]
                    default: "--view-all"
                    example:
                        - "--view-all"
                        - "--edit-all"
