definitions:
  Patient:
    properties:
      name:
        type: string
        required: true
      birthdayDate:
        type: string
        required: true
      patientNumber:
        type: number
        required: true
        unique: true
      status:
        type: string
        enum: ["Suspect", "Infected", "Non Infected"]
        default: "Suspect"
      contacts:
        type: object
        properties:
          phone:
            type: number
            minLength: 9
            maxLength: 9
            required: true
            unique: true
          email:
            type: string
            unique: true
            format: email
            required: true
            pattern: '/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$'
      symptoms:
        type: array
        items:
          type: string
          enum:
            [
              "cough",
              "fever",
              "shortness of breathe",
              "lack of smell",
              "lack of taste",
              "tiredness",
              "burning eyes",
              "headaches",
              "diarrhea",
            ]
      meta:
        type: object
        properties:
          createdAt:
            type: string
            format: date
          updatedAt:
            type: string
            format: date
