definitions:
  User:
    properties:
      name:
        type: string
        required: true
      email:
        type: string
        unique: true
        format: email
        required: true
        pattern: '/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$'
      role:
        type: string
        format: uuid
      password:
        type: string
        unique: true
        required: true
      createdAt:
        type: string
        format: date
      updatedAt:
        type: string
        format: date
